### ISSUE TITLE
客户端界面

### ISSUE THREAD

**Issue by HugheHuang** [jianyueAPP/jianyue#2]

**Comment by egbertwong** [comment]
1. 新用户欢迎

- [ ] 欢迎页界面

- [ ] 新用户兴趣标签选择

2. APP 主界面 

- [ ] 界面 UI 设计
- [ ] 刷新（下一篇文章）

- [ ] 兴趣标签选择（选择后下次刷新可显示相关文章）

- [ ] 更改字体

- [ ] 更改背景

- [ ] 收藏

- [ ] .收藏夹

- [ ] 意见反馈
